import Head from "next/head";
import styles from "./Layout.module.css";

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Asseessment</title>
        <meta name="Assessment" content="Generated by uncle" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>{children}</div>
    </div>
  );
}
