import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import MainSection from "../components/MainSection/MainSection";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by uncle" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainSection />
      <Footer />
    </div>
  );
}
